import {toTimestampSeconds} from "./cookie_details";
import {OWNER_NAME, OWNER_WEBSITE_URL} from "../config";

export const formatCookies = (cookies, format = "header_string") => {
    switch (format) {
        case "netscape":
            return [
                "# Netscape HTTP Cookie File",
                `# This file was generated by Cookie Editor - ${OWNER_NAME} ${OWNER_WEBSITE_URL}`,
                ...cookies.map((cookie) => {
                    const expirationDate = toTimestampSeconds(cookie.expirationDate)
                        || Math.round(Date.now() / 1000) + 86400;
                    const domain = cookie.domain || "";

                    return [
                        `${cookie.httpOnly ? "#HttpOnly_" : ""}${domain}`,
                        String(domain.startsWith(".")).toUpperCase(),
                        cookie.path || "/",
                        String(Boolean(cookie.secure)).toUpperCase(),
                        expirationDate,
                        cookie.name,
                        cookie.value,
                    ].join("\t");
                }),
            ].join("\n");

        case "json":
            return JSON.stringify(cookies, null, 2);

        case "header_string":
        default:
            return cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join("; ");
    }
};
